version: '3'

services:

  php:

    container_name: php8124

    restart: always

    image: rtmp_server_php

    build:

      context: ./

      dockerfile: Dockerfile

    ports:
      # http-flv/ws-flv
      - "8501:8501"
      - "8502:8502"
      - "8503:8503"
      - "8504:8504"
      - "8505:8505"
      - "8506:8506"
      - "8507:8507"
      - "8508:8508"
      # rtmp
      - "1935:1935"
      # web
      - "80:80"
      - "443:443"
      # flv gateway
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      # file gateway
      - "8100:8100"
      - "8101:8101"
      - "8102:8102"
      - "8103:8103"

      # websocket
      - "8088:8088"
      - "8089:8089"
      - "3478:3478"

    volumes:
      - ./:/usr/src/myapp

    tty: true

    ulimits:
      nofile:
        soft: 65535
        hard: 65535

    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.tcp_max_syn_backlog: 65535
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.tcp_fin_timeout: 15

networks:
  bridge:
    driver: host
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
