version: '3'

services:

  php:

    container_name: my_php_8

    restart: always

    image: my_php_8

    build:

      context: ./

      dockerfile: Dockerfile

    ports:
      - "8501:8501" # http-flv/ws-flv流媒体服务
      - "8502:8502" # http-flv/ws-flv流媒体服务
      - "8503:8503" # http-flv/ws-flv流媒体服务
      - "8504:8505" # http-flv/ws-flv流媒体服务
      - "1935:1935" # rtmp流媒体服务
      - "80:80" # 默认的web服务
      - "443:443" # 默认的ssl服务
      - "8080:8080" # 默认的flv网关服务
      - "8081:8081" # 备用的flv网关服务
      - "8082:8082" # 备用的flv网关服务
      - "8083:8083" # 备用的flv网关服务
      - "8100:8100" # 静态文件file网关服务
      - "8101:8101" # 备用静态文件file网关服务
      - "8102:8102" # 备用静态文件file网关服务
      - "8103:8103" # 备用静态文件file网关服务

    volumes:
      - ./:/usr/src/myapp

    tty: true

    ulimits:
      nofile:
        soft: 65535
        hard: 65535

    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.tcp_max_syn_backlog: 65535
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.tcp_fin_timeout: 15

networks:
  bridge:
    driver: host
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
